name: GuildedRose CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'temurin'

            - name: Build with Gradle Wrapper
              run: ./gradlew build
